### ISSUE TITLE
Getting ERROR TypeError: Object(...) is not a function #

### ISSUE THREAD

**Issue by albertthinc** [formly-js/ngx-formly#1248]
Hi

I am using the beta version of ngx-formly core and bootstrap. Rxjs 6.3.3 and rxjs-compat also latest.

The application working fine in my local.

When I build the files and use it in a maven application working fine.

But when the files are deployed to server, I am getting the typeerror object is not a function.

Can you help please. I am in a critical situation.

Thank you

**Comment by aitboudad** [comment]
I'm not sure this is related to formly lib and without providing a reproduction we can't help, sorry about that!

**Comment by aitboudad** [comment]
I've tried my app that use formly beta version with prod build and it seems working very well,
the error log is not helpful,  that kind of issue require debugging in order to guess what's going wrong.

since it's working on dev env probably related to the angular cli optimizer could you try disabling buildOptimizer:
```json
  "buildOptimizer": false,
```

**Comment by albertthinc** [comment]
I removed all my code and added a single textbox. 
Still getting the error as object is not a function.

 View_formlyfieldinput_0 formlyfactory.js

**Comment by albertthinc** [comment]
When I click the page the same error add again and again..

Used the formlymodule in a shared module.

**Comment by albertthinc** [comment]
Which version of angular core I have to use..?

**Comment by aitboudad** [comment]
I don't know whithout a reproduction, I can't help!
