### ISSUE TITLE
Lifecycle onChanges not working

### ISSUE THREAD

**Issue by Knoxvillekm** [formly-js/ngx-formly#390]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

Lifecycle onChanges not working

**Expected behavior**

After change text in intup trigger onChanges from Lifecycle

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/IGjGuXvJ73eP9GB10D60?p=preview

**Comment by franzeal** [comment]
I'm not convinced that `onChanges` isn't working as intended (I wouldn't expect this to fire unless the inputs on the `FormlyField` are changing).

If you're wanting to respond to changes in the value of the field, there's the templateOptions.change handler for that (which appears to be debounced).  If that's what you're after, see here:  https://plnkr.co/edit/ChMyhwC8UpRZwF5XHz52?p=preview

I've also enabled production mode in that plunk due to errors unrelated to your question.

**Comment by Knoxvillekm** [comment]
How to use ngModelChange?

**Comment by franzeal** [comment]
I think you should be able to subscribe to `modelChange` from the `onInit` lifecycle hook.  Keep in mind, this is effectively a subscription to the `formControl.valueChanges` for the field because these are reactive forms.

You could make the subscription/unsubscription simpler by implementing this as a `to` hook for a custom field type or base class that all your custom field types inherit from.

I'm not aware of anything existing that is equivalent, but I still think `templateOptions.change` may be the intended equivalent.  @aitboudad or @mohammedzamakhan would be the one's who could say definitively.

**Comment by aitboudad** [comment]
The best approach to me is to rely on what angular provides (subscription to `formControl.valueChanges`)

**Comment by rjsteinert** [comment]
I found [this example](https://stackoverflow.com/a/34616143) useful. `this.form.valueChanges.subscribe(data => console.log('Form changes', data));`

**Comment by timvandesteeg** [comment]
@franzeal The provided plunker seems to be broken (https://plnkr.co/edit/ChMyhwC8UpRZwF5XHz52?p=preview).
I think that contained an answer to my problem. I can't get the change event to work in the templateOptions. However, the blur event does work. Added a simplified version of my code below. I'm using @angular/material 5.0.3 if that matters.

`templateOptions: {
          blur: () => {
            setTimeout(() => { console.log('this works'); }, 200);
          },`

**Comment by franzeal** [comment]
@timvandesteeg I can't get that plunker either.  We can work from here:
https://stackblitz.com/edit/angular-a8cpa6

This uses the field's onInit lifecycle hook to subscribe to the form control's valueChanges, which is recommended.

**Comment by timvandesteeg** [comment]
@franzeal Thank you for your response. That version is using the bootstrap templates instead of the material templates. I'm kind of new to stackblitz, but I can't seem to change it to the material variant without generating errors not related to this issue.
I tried your suggestion of the change and onInit functions, but both are not working locally. Maybe it is @ngx-formly/material specific?

**Comment by franzeal** [comment]
@timvandesteeg The blur/change appear to function correctly.  The lifecycle hook does not appear to get called.  I would recommend finally separate issue.

https://stackblitz.com/edit/angular-obhjjx?embed=1&file=app/app.component.ts

**Comment by franzeal** [comment]
@timvandesteeg I've created a PR to address the material issue:
https://github.com/formly-js/ngx-formly/pull/628

**Comment by franzeal** [comment]
@timvandesteeg I've created a PR to address the material issue:  https://github.com/formly-js/ngx-formly/pull/628

**Comment by aitboudad** [comment]
released a new version `2.0.0-rc.7`.

**Comment by aitboudad** [comment]
The blur/change work only for input type, seems we have to explicitly define them on all custom material component, I'm going to fix that too!

**Comment by aitboudad** [comment]
Do you think guys introduction a `watcher` property would simplify things here:

Before: 

```ts
lifecycle: {
  onInit: function(form, field) {
    field.formControl.valueChanges.subscribe(v => {
      console.log('valueChanges', v);
    });
  }
}
```
After

```ts
watcher: function(form, field) {
  console.log('valueChanges', field.formControl.value);
}
```
