### ISSUE TITLE
maxlength exceeded

### ISSUE THREAD

**Issue by nikul1993** [formly-js/ngx-formly#471]
Hello Team,

Right now we are using Validators.maxLength(10) for the max length and after it goes to more then 10 character it shows message but it is possible to prevent the keyboard typing...?

like this https://plnkr.co/edit/PPe2srNajki0PFGHHmdk?p=preview in name field after 24 character it cannot type any thing.

thanks

**Comment by franzeal** [comment]
Here is one approach that would involve providing a custom input type:
https://plnkr.co/edit/bJoAfePwEbPkk0hziU5m?p=preview

**Comment by nikul1993** [comment]
Hello @franzeal ,

I Seen your demo and we want exactly like that but can you please add those functionality  into plugin ..?
so we can manage perfectly in our project 
we really appreciate 😄 

Thanks

**Comment by ultimafirez** [comment]
As with the original angular formly, this is not default behaviour. I don't see how or why the custom input type provided by @franzeal would be harder to manage in your project. 

There are definitely use cases where certain requirements for a project would allow for users to type beyond the max length, showing validation when the user does exceed this max length. With that said, its easier to just allow users of ng-formly to create a custom type rather than shoehorn in the maxlength as default (even though it might be intuitive to do so).

**Comment by franzeal** [comment]
I definitely encourage getting comfortable with using custom types.

There's a lot of documentation between the [demo](https://github.com/formly-js/ng-formly/tree/master/demo/src/formly) and the [website](https://ng2.angular-formly.com/guides/ng-bootstrap-timepicker.html) that demonstrate extensability of formly specifically through custom types.  The only thing unique in this instance is that in the examples I've provided I'm effectively overloading the type used by the bootstrap-ui module if you've imported it.

As for adding this feature to the project, I'd want @mohammedzamakhan or @aitboudad to weigh-in.  It's a trivial PR, but the existing types are pretty minimal and I don't necessary want to go against the grain particularly when extending formly to meet your own needs is highly encouraged.

**Comment by mohammedzamakhan** [comment]
I personally would love to see #253 to be resolved which let's you add dynamic attributes to the type. That would let a lot of cases where you have to create new type eliminated. 

Extending a type and using a new type component would be helping in your case

**Comment by aitboudad** [comment]
here is my proposal https://github.com/formly-js/ngx-formly/pull/736
