### ISSUE TITLE
Checkbox indeterminate state

### ISSUE THREAD

**Issue by davidoween** [formly-js/ngx-formly#674]
Hello, 

How can I assign a default value to checkbox. I tried with defaultValue: true, but it does not work.

Or how can I remove the "indeterminate view-state" of a checkbox.

https://css-tricks.com/wp-content/uploads/2011/08/checkboxstates.png  

<img width="199" alt="capture" src="https://user-images.githubusercontent.com/20514968/35327207-554c9e36-00f9-11e8-9a00-52c3e298b48b.PNG">

Thanks

**Comment by Pat-Lovelace** [comment]
I would like to remove the state 'indeterminate', because sometimes I won't have an initial model for a checkbox type field, and I don't want an 'indeterminate' state, I mean, instead of a 'dash' checkbox, I want to see a empty checkbox. 

Is there any way to avoid this state? 
For instance, modifying the JSON field of a checkbox type field:
``` json 
{
      key: 'example',
      type: 'checkbox',
      templateOptions: {
        label: 'example',
        indeterminate: false
      },
}
```

Having a initial model like: example = false, it's not a solution for me.

**Comment by Pat-Lovelace** [comment]
Now it's perfect! Thanks! ;)
