### ISSUE TITLE
Custom control templates

### ISSUE THREAD

**Issue by juristr** [formly-js/ngx-formly#690]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**What is the motivation / use case for changing the behavior?** . 
I'm currently giving `ngx-formly` a closer look as I would like to use it in one of our applications. The support question I'm having is whether it is possible to provide some custom components (obviously they have to integrate with - say - reactive forms (implementing ValueAccessor and what not). Like when I'm having my custom autocomplete, or custom checkbox etc.

Is that already possible? Searched a bit in the docs but didn't find anything. Maybe I miss it 😄. Thx 

* **Angular version:** 5.1.0

**Comment by aitboudad** [comment]
hi, I think it's possible see:

- https://formly-js.github.io/ngx-formly/examples/other/input-file
- https://formly-js.github.io/ngx-formly/examples/other/button

**Comment by juristr** [comment]
@aitboudad oh, my bad, how could I miss those 🤔. Thx. closing this issue, in case I'll reopen again 😉

**Comment by aitboudad** [comment]
you're more than welcomed :1st_place_medal:

**Comment by chaosLegacy** [comment]
Hi sir, I've start using formly today and i really start to like it, yet i have a problem is that i'm looking for a way to inject a multi select Dropdown using this library [https://cuppalabs.github.io/components/multiselectDropdown/](url) for a project that i'm working on, so i need to call this directive in order to make my multi select Dropdown visible like this 
`<angular2-multiselect [data]="dropdownList" [(ngModel)]="selectedItems"
                            [settings]="dropdownSettings"
                            (onSelect)="onItemSelect($event)"
                            (onDeSelect)="OnItemDeSelect($event)"
                            (onSelectAll)="onSelectAll($event)"
                            (onDeSelectAll)="onDeSelectAll($event)">
      </angular2-multiselect>`
I couldn't find any way on your documentation showing how you can customize an input, I'm suggesting something like this:
`templateOptions: {
        html: '<angular2-multiselect [data]="dropdownList" [(ngModel)]="selectedItems"
                            [settings]="dropdownSettings"
                            (onSelect)="onItemSelect($event)"
                            (onDeSelect)="OnItemDeSelect($event)"
                            (onSelectAll)="onSelectAll($event)"
                            (onDeSelectAll)="onDeSelectAll($event)">
      </angular2-multiselect>',
      },`
Thanks a lot I appreciate your efforts

**Comment by aitboudad** [comment]
@chaosLegacy you should create a custom type here is a quick example https://stackblitz.com/edit/angular-kzci2z?file=app%2Fapp.module.ts

**Comment by chaosLegacy** [comment]
Thanks bro you're the best
