### ISSUE TITLE
Is there any support for Angular Data-Table ?

### ISSUE THREAD

**Issue by Rakesh2003** [formly-js/ngx-formly#965]
Can you please explain how to integrate angular-datatables ? 

Reference :- https://l-lin.github.io/angular-datatables/#/advanced/dt-instance

 angular-datatables has several features like pagination, sorting, column reorder, select row etc. that we find quite useful.

**Comment by juristr** [comment]
@Rakesh2003 How did you think of integrating a data table into a form? Like what's your use case?

I'm asking since I probably wouldn't integrate it within an Angular form directly. But if you really want, you can always implement a custom type and register it with ngx-formly. Check out the [guide on how to create a custom wrapper](https://formly-js.github.io/ngx-formly/guide/custom-formly-wrapper). Maybe that helps 😄

**Comment by Rakesh2003** [comment]
There is already one example explaining datatables uses in form discussed in thread https://github.com/formly-js/ngx-formly/issues/701
As this example uses **ngx-datatable** ( https://stackblitz.com/edit/angular-gmswdm ).
However we find angular-datatable has rich features and looking for integration sample for this.

**Comment by aitboudad** [comment]
not sure if possible with a smooth way they provide their own solution https://editor.datatables.net/, the only easy way to integrate it, is to edit a row withing a modal that render ngx-formly form.

**Comment by aitboudad** [comment]
@juristr welcome to the `formly-js` family (didn't know you've been added to the team) :tada: :tada:
